---
# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/andre-marcos-perez/ifood-mlops-app -------------------------
# ----------------------------------------------------------------------------------------
version: "3.6"
volumes:
  sandbox:
    name: "sandbox"
    driver: local
services:
  jupyterlab:
    image: sandbox:latest
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - sandbox:/opt/workspace
...